### ISSUE TITLE
Show watts ? 

### ISSUE THREAD

**Issue by schabrolles** [rurza/BatFi#1]
Very nice App !!! 
Works perfectly.

Do you think you could add the current Watts used by the MAC ?
This could be interesting to have it when we click on the icon. What do you think ? 
<img width="253" alt="image" src="https://github.com/rurza/BatFi/assets/19491077/7a15f7f5-3244-4a89-808e-92f12a322efc">

I currently use a second app for that, but I think it is good to have everything in your app.
The best of the best would be to have :
  - Macbook current watt usage when disconnected 
  - Macbook current watt received when charging

**Comment by rurza** [comment]
Hey! Not a bad idea :)
Do you know what API this app uses?:)

**Comment by schabrolles** [comment]
I really don't know :) 
I use this App that report battery status : https://apps.apple.com/app/id836505650?mt=12

**Comment by hiroshi80** [comment]
I'm constantly checking for apps that are consuming too much power⚡️.
So, I would be happy if the BatFi would notify me when the power consumption exceeds the threshold.

**Comment by rurza** [comment]
I will add it with 1.4.0 :) There is a working version on the develop branch (thanks to @decodism), but I would like to polish the UI and I noticed that it once stopped working. I have to double check it before the release :)
