### ISSUE TITLE
MacOS Sonoma Support

### ISSUE THREAD

**Issue by pangzi499** [rurza/BatFi#10]
Pls add MacOS Sonoma Support, Thx.

**Comment by rany2** [comment]
At least 1.3.0 and 1.3.1 work fine on MacOS Sonoma for me. Are there any issues on Sonoma?

**Comment by pangzi499** [comment]
Hi adam,
I got a new issue(In fact, I cannot confirm yet).

[image: image.png]
I cannot charge up to 100%.

14.0 (23A344)
1.3.1(17)


Best,
Stephen

Adam Różyński ***@***.***> 于2023年10月13日周五 06:33写道：

**Comment by pangzi499** [comment]
after sent last email, it's still show the 82%
[image: image.png]

pangzi Mr ***@***.***> 于2023年10月18日周三 13:09写道：

**Comment by pangzi499** [comment]
[image: image.png]
It seems that it is working normally now.

pangzi Mr ***@***.***> 于2023年10月18日周三 15:23写道：

**Comment by rurza** [comment]
@pangzi499 Please create a new issue and post images directly from Github instead of replying via email every time in this thread.
