### ISSUE TITLE
Menu shows Battery Health at 101%

### ISSUE THREAD

**Issue by gsohoni** [rurza/BatFi#21]
On M3 Pro, the BatFi menu is showing Battery Health at 101%.
<img width="245" alt="Screenshot 2023-12-14 at 09 15 24" src="https://github.com/rurza/BatFi/assets/298284/92ba0e45-edc7-4366-bd84-1bfb2f05029b">

**Comment by rurza** [comment]
Thanks! Right now the app calculates the health by dividing the capacity reported by the battery by the original capacity, so for a new battery it can be more than 100%. I'm going to change the implementation, because it's off to numbers reported by the System Settings
