### ISSUE TITLE
A way to customize the 2nd section in the menu bar ?

### ISSUE THREAD

**Issue by SaddemAmine** [rurza/BatFi#28]
Would be cool if we can choose what to keep here
<img width="263" alt="image" src="https://github.com/rurza/BatFi/assets/47611308/88c4a58d-5c8f-4ba5-a6d7-88afebc4cf2c">
--- 
The cycle count and battery percentage aren't things that I want to look at all the time, any chance we get the option to customize that section ?

**Comment by pchmykh** [comment]
Agree. Battery health and cycle count for example is totally technical information and it is a good idea to have hide option for them.

**Comment by rurza** [comment]
Done with BatFi 2
