### ISSUE TITLE
Update to Version 1.4.1 (32) has all the language set to cyrillic characters

### ISSUE THREAD

**Issue by rna84** [rurza/BatFi#30]
I've updated today to the newer version but now all the text is set to cyrillic characters instead of English (or latin characters) - I'm on MacOS Sonoma
<img width="304" alt="Screenshot 2024-02-04 alle 08 15 45" src="https://github.com/rurza/BatFi/assets/152380469/b08a128b-57f7-46ec-bd3e-0f362fcabb59">
<img width="249" alt="Screenshot 2024-02-04 alle 08 15 41" src="https://github.com/rurza/BatFi/assets/152380469/e443d70e-df93-489a-9350-4a9c99b23cb9">

**Comment by rurza** [comment]
Hey @rna84 :)
What language do you have set in System Settings? (Open System Settings -> General -> Language & Region)

**Comment by rna84** [comment]
I think I've fixed it, I had Russian set on it - now by setting another language is everything fine. Thanks!
