### ISSUE TITLE
Energy distribution not available on last update

### ISSUE THREAD

**Issue by Neifab** [rurza/BatFi#37]
Hello,

There is a bug of the function on the last update, 1.4.2 (34).

Thank you

![screenshot](https://github.com/rurza/BatFi/assets/76597174/beeec465-c2e0-429b-a013-4ab30b60c4fd)

**Comment by rurza** [comment]
Hey!
Thanks for reporting it. The build 40 fixed the problem, didn't it? :)

**Comment by Neifab** [comment]
Yes it is !
