### ISSUE TITLE
Feature request – Magsafe led control

### ISSUE THREAD

**Issue by Joan** [rurza/BatFi#65]
Hi,
It's great to discover this open-source alternative to AD (and with a _way better_ UI)!
The only thing I'd miss is the Magsafe LED control (turn green when reaching the limit, orange while charging).
I hope this could be considered in a future update!

**Comment by rurza** [comment]
This functionality is already available :)

**Comment by Joan** [comment]
Oh what a surprise! I must have missed it when I was looking for this…
Thanks for your answer and for this app!
