### ISSUE TITLE
BatfiHelper

### ISSUE THREAD

**Issue by taktokhm** [rurza/BatFi#66]
BatfiHelper isn't functioning in macos sequoia; I know sequoia isn't a public release and still under development, so I don't expect this issue to be fixed anytime soon, but I in case the issue maybe isn't about macos version I'll be glad if this bug get fixed in the next update.
![Screenshot 2024-07-08 at 7 50 00 PM](https://github.com/rurza/BatFi/assets/72253833/1624dee9-7211-497f-8e5d-34f8a460804f)

**Comment by rurza** [comment]
Which version of macOS beta do you have?

**Comment by taktokhm** [comment]
15.0 Beta (24A5264n)

**Comment by rurza** [comment]
Please update macOS to the latest beta.
