### ISSUE TITLE
Menubar icon showing exclamation mark and Power Distribution always waiting for Data

### ISSUE THREAD

**Issue by RuochenFu21** [rurza/BatFi#67]
Like this: 
<img width="243" alt="Arc 2024-07-09 19 45 51" src="https://github.com/rurza/BatFi/assets/62882800/b2d81e9b-84d1-4f0d-bc79-878038612d62">
(Mac OS 15 Beta, most recent version of BatFi)

**Comment by RuochenFu21** [comment]
Uh how to solve this?

**Comment by rurza** [comment]
Please follow up the troubleshooting section on app's website:

https://micropixels.software/apps/batfi#faq

**Comment by RuochenFu21** [comment]
App mode stayed at Initializing after try to following the procedure under "I've set the limit, but the battery keeps charging". I couldn't find BaFi.app in "Allow in the Background" but found "BatFiHelper" and it was enabled. What to do now?

**Comment by rurza** [comment]
If you're using macOS **DEVELOPER BETA** consider the following:
- always use the latest version before reporting an issue
- avoid using it if you’re not a macOS developer. It’s intended for developing apps, so it’s completely expected that third-party apps may not work properly

**Comment by 0PandaDEV** [comment]
I have the same issue, I'm on a fresh installation of macOS Sequoia.

**Comment by MasterofDeath01** [comment]
Facing this same problem on Sonoma 14.8.3

Do you know how to fix it?

**Comment by sudocheckmate** [comment]
> Facing this same problem on Sonoma 14.8.3
> 
> Do you know how to fix it?

Install an app called Battery in the app store by some Chinese dev - it's free. Batfi no longer works with the latest updates of Sonoma
