### ISSUE TITLE
New menu bar icon & font

### ISSUE THREAD

**Issue by Neifab** [rurza/BatFi#78]
Hello everyone,

Just installed the new 2.1.0 beta and noticed an new icon and font size for the menu bar. It is the new standard for the next MacOS ?

It's not "bad", but the previous one was the perfect size compare to this one, more tiny and with a smaller text.

Thank you

**Comment by rurza** [comment]
Hey!
So, is it good?:)

**Comment by Neifab** [comment]
> Hey! So, is it good?:)

Yes, it was strange to see it changed and be the new default parameter now. Maybe the pourcentage font when it's showed on the side of the icon is too small.
