### ISSUE TITLE
Can't inhibit charging on sleep mode

### ISSUE THREAD

**Issue by berkeenesakt** [rurza/BatFi#82]
After macOS Sequoia update app stopped inhibit charging on sleep mode. I enabled charge limit on sleep mode. 
<img width="692" alt="Screenshot 2024-09-21 at 08 36 48" src="https://github.com/user-attachments/assets/cff7367d-03e9-45f1-84a5-6a4876a3424e">

**Comment by manishdm123** [comment]
I have noticed the same issue

**Comment by berkeenesakt** [comment]
It's really huge problem makes the application non-functional. We are waiting fix asap @rurza 🙏

**Comment by Sin-cy** [comment]
Yeah its happened after the Mac OS Sequoia update.

**Comment by rurza** [comment]
Hey folks!
Did you tried the latest BatFi Beta? :)

**Comment by Sin-cy** [comment]
@rurza I just got an update for version 2.1.0. Read the patch notes. Thank you.

> Hey folks! Have you tried the latest BatFi Beta? :)

**Comment by rmaprojects** [comment]
Now, inhibit charging on sleep mode is completely disappear anyone know how to turn it back?


<img width="692" alt="Screenshot 2024-09-23 at 20 52 29" src="https://github.com/user-attachments/assets/59dc9c98-de71-4cb2-89c0-fa1dc6e0be48">

**Comment by berkeenesakt** [comment]
I think it's removed. 

Anyone using this version of macOS, or those who updated it on a separate volume, will lose this functionality, even when running macOS 13 or 14. The update hides the toggle switch in the app’s settings for macOS 15 users

**Comment by berkeenesakt** [comment]
@rurza I saw on another app, there is another option for stop charging when Mac goes sleep instead of limit charging. Can you add it to BatFi?

**Comment by rurza** [comment]
Please update the app to the latest version. Everything is explained in the changelog.

**Comment by Kitround** [comment]
Hello, i'm on the last Sonoma 14.7.6 and the 2 options are not working. I am ending with a battery fully charge. Thanks
